https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [1]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3, 4))

array([[0.87367189, 0.6322729 , 0.29667214, 0.73508148],
       [0.13753344, 0.45523897, 0.63842007, 0.06293296],
       [0.75381864, 0.7109387 , 0.24546017, 0.10881324]])

In [2]:
from numpy.random import normal

normal_value = normal(size = (3, 4))
#ndarray常用的實體屬性
type(normal_value) #傳出：numpy.ndarray，此為實體
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [3]:
#ndarray的陣列運算
normal_value * 10

array([[  1.02319177,  -8.31126583,  -3.47203844, -10.64390336],
       [ -0.75056559, -21.41549777, -10.86830524,   3.65876506],
       [ 21.21509652,  -4.1755601 ,   8.26430408, -17.17081899]])

In [17]:
#ndarray的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([0.15830357, 1.66656118, 1.54796039])

### axis
在NumPy中，axis（軸）表示陣列的維度或座標軸方向，用來指定沿著哪個維度進行操作：   
- NumPy的陣列是多維的，每個維度稱為一個軸（axis）。   
- axis的編號從0開始，依序表示第1維、第2維、第3維……，依此類推。   
- 對於二維陣列：   
    - axis=0表示沿著縱軸方向（從上到下），即跨列方向(對每一欄求和)
    - axis=1表示沿著橫軸方向（從左到右），即跨欄方向(對每一列求和)   
- 操作時，指定axis=i表示沿第i個軸進行計算，計算時會「折疊」該軸，即該軸上的元素被聚合，結果陣列的維度會減少該軸對應的維度。