https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [ ]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3, 4))
np.random.random(size=(3, 4))

array([[0.6468293 , 0.1861603 , 0.06840228, 0.82242379],
       [0.88178276, 0.96095679, 0.07526484, 0.84029658],
       [0.01521338, 0.86353145, 0.67127613, 0.94998836]])

In [12]:
from numpy.random import normal

normal_value = normal(size = (3, 4))
#ndarray常用的實體屬性
type(normal_value) #傳出：numpy.ndarray，此為實體
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [13]:
#ndarray的陣列運算
normal_value * 10

array([[  9.66931433,  -4.54169165,  12.69881937, -16.24340631],
       [ -1.01482903,   1.67824312,  12.57138024,   3.43081744],
       [ 20.0381205 ,  -8.14737961,  -7.91876467,  11.50762766]])

In [ ]:
#ndarray的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([0.15830357, 1.66656118, 1.54796039])

## axis
在NumPy中，axis（軸）表示陣列的維度或座標軸方向，用來指定沿著哪個維度進行操作：   
- NumPy的陣列是多維的，每個維度稱為一個軸（axis）。   
- axis的編號從0開始，依序表示第1維、第2維、第3維……，依此類推。   
- 對於二維陣列：   
    - axis=0表示沿著縱軸方向（從上到下），即跨列方向(對每一欄求和)
    - axis=1表示沿著橫軸方向（從左到右），即跨欄方向(對每一列求和)   
- 操作時，指定axis=i表示沿第i個軸進行計算，計算時會「折疊」該軸，即該軸上的元素被聚合，結果陣列的維度會減少該軸對應的維度。